### ISSUE TITLE
It just stopped working. Vscode 1.27.2, Ubuntu 14.04

### ISSUE THREAD

**Issue by hbdevelop1** [amos402/vscode-scope-bar#10]
I am using vscode Version: 1.27.2, on Ubuntu 14.04
The extension just stopped working, I believe after I updated vscode, lately.
My attempts to get it to work include:
-Uninstalling the extension, closing vscode, restarting it, installing the extension, closing vscode and restating it again.
-Disabling and then enabling the extension.
None of that worked.
Any idea ?
Thanks

**Comment by hwsoderlund** [comment]
I think I have this problem too. Not sure if it is exactly the same. The bar always says "Global Scope" now, no matter where I put the cursor. @hbdevelop1 does it say anything at all in your bar, or is it just empty? 

I have tried this with .py, .js, and .go files. Exactly the same. Always "Global Scope".

```
macOS Mojave 10.14
VS Code Version 1.28.2 (1.28.2)
```

**Comment by amos402** [comment]
It seems there are some changes of vscode's api. I will fix it latter.

**Comment by hwsoderlund** [comment]
Perfect. And thanks for an awesome extension!

**Comment by luckcolors** [comment]
@amos402 any updates on making this working again? Thanks for making this amazing extension :)

**Comment by amos402** [comment]
😭Oops, sorry guys, I just forgot this issue for a while......
I just update a version for that, It should works.

**Comment by luckcolors** [comment]
Hello. I've installed the latest update and it still doesn't work.
Could it be that it doesn't support a programming language? I'm using it with golang. (see here https://github.com/Microsoft/vscode-go)

**Comment by amos402** [comment]
@luckcolors Fixed that, you can upgrade from market now.

**Comment by luckcolors** [comment]
@amos402 thanks! It seems to be working correctly now. :D

**Comment by luckcolors** [comment]
Just noticed that opening the the menu listing of the scopes is empty.
Now it does though correctly display the current scope.

**Comment by xgdgsc** [comment]
It always says "Global Scope" now for me on ubuntu 16.04.

**Comment by amos402** [comment]
@xgdgsc Did you confirm you have the language service match your current language?
You can use command `@` for a check.

**Comment by xgdgsc** [comment]
Yes. I use cpp and @ shows functions. Clicking on status bar  "Global Scope"  also shows a list of functions.

**Comment by amos402** [comment]
> 
> 
> Yes. I use cpp and @ shows functions. Clicking on status bar "Global Scope" also shows a list of functions.

I see, if you're using `ms-vscode.cpptools`, with cpp files, all functions treat as global functions, that's because the extension didn't provide the symbols' depth. But since `ms-vscode.cpptools` already provide a navigation feature, you can just simply use it.

**Comment by xgdgsc** [comment]
Where is that navigation feature?

**Comment by amos402** [comment]
@xgdgsc You can easy to find out that on status bar after you install `ms-vscode.cpptools`.
I think we're getting far off the issue, I'm closing this issue, if you have any other issue feel free to create a new one.
