### ISSUE TITLE
Cannot read property 'iterNodesRevers' of undefined: TypeError: Cannot read property 'iterNodesRevers' of undefined

### ISSUE THREAD

**Issue by jens1o** [amos402/vscode-scope-bar#5]
Cannot read property 'iterNodesRevers' of undefined: TypeError: Cannot read property 'iterNodesRevers' of undefined
	at ScopeFinder.<anonymous> (C:\Users\Jens\.vscode-insiders\extensions\amos402.scope-bar-0.0.3\out\src\scope.js:147:46)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\Jens\.vscode-insiders\extensions\amos402.scope-bar-0.0.3\out\src\scope.js:4:58)
	at <anonymous>
e.onUnexpectedError @ shell.ts:459
(anonymous) @ shell.ts:419
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:138
e.$onUnexpectedError @ mainThreadErrors.ts:26
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:36
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560

Could you fix that bug please?

**Comment by amos402** [comment]
Could you take more information about that? How does it happen? 
Which language do you use?

**Comment by jens1o** [comment]
I can't reproduce it anymore at the moment. I'll get back to you once I'm able to do that. :) Thanks!
