### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mathritter** [amos402/vscode-scope-bar#8]
Using with php, framework cakephp. Not working at the moment, any idea?

![image](https://user-images.githubusercontent.com/6000689/42036164-0afc5844-7abb-11e8-8a22-2eeb85740f70.png)

**Comment by amos402** [comment]
@mathritter Did you install any php extension? Does your `@` command work?
I tried with [PHP IntelliSense](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense), it seems to work fine.

![default](https://user-images.githubusercontent.com/3406561/42046794-3ca7ea5e-7b31-11e8-8bed-dcf345a3bf82.png)

**Comment by mathritter** [comment]
Yeah, I have few extensions:
![image](https://user-images.githubusercontent.com/6000689/42166008-16a77df4-7de0-11e8-8d43-0fb4d4f89deb.png)

**Comment by mathritter** [comment]
Trying this @ command, I guess it's not working

**Comment by amos402** [comment]
@mathritter Scope bar is base on the language extension whitch it provide symbols service. If your @ command doesn't work, scope bar either.
It seems that you only have a debug extension, you can try install [PHP IntelliSense](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense), thereafter, it should works.

**Comment by mathritter** [comment]
Unfortunately I can't use PHP IntelliSense, we're on php 5.6.30. Any advice?

**Comment by amos402** [comment]
@mathritter  Try this extension [PHP Intellisense - Crane](https://marketplace.visualstudio.com/items?itemName=HvyIndustries.crane), it works well on php5.

**Comment by mathritter** [comment]
Well, thanks, that worked pretty well!
