### ISSUE TITLE
Add Vue support

### ISSUE THREAD

**Issue by DTX-92** [amos402/vscode-scope-bar#9]
I expected to see 'plotAverage' function but extensions says 'Global Scope'
![image](https://user-images.githubusercontent.com/20479161/46083715-b03a1e00-c1aa-11e8-8cca-596700d8e338.png)

**Comment by amos402** [comment]
Hey @DTX-92, What extension of Vue do you use?
I tried on [Vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur), it seems work.
This extension doesn't provide any symbols provider, you should assume that you have extensions can provide language feature.
![default](https://user-images.githubusercontent.com/3406561/46095441-26607400-c1ef-11e8-89d9-10531bbba774.png)

**Comment by DTX-92** [comment]
@amos402, I didnt use i could use methods like this:
```
methods: {
  foo() {

  }
}
```
It helped, thank you!

The problem was with anonymous functions.
